### ISSUE TITLE
Add rolebinding clusterrolebinding names in the display

### ISSUE THREAD

**Issue by HenryXie1** [reactiveops/rbac-lookup#19]
It is ER that if we can add rolebinding clusterrolebinding names in the display, it would be helpful
as users struggle to find out which subject is related to which rolebinding .
thanks

**Comment by sudermanjr** [comment]
@HenryXie1 Thanks for the issue.  Have you tried using the output flag `-o wide`?  I believe this will provide the info you are looking for.

**Comment by HenryXie1** [comment]
Thanks Andrew. That works.
